apiVersion: v1
kind: PersistentVolume
metadata:
  name: dev-documentos
  namespace: mineco-dev
  labels:
    comercio: ready
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  # hostPath:
  #   path: "/deployment/application/desarrollo/documentos/comercio"
  nfs:
    server: 128.5.8.222
    path: "/deployment/comercio"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dev-documentos
  namespace: mineco-dev
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      comercio: ready
